seed: 42

n_timesteps: !!float 1e8
policy: 'MlpPolicy'

n_steps: 60
n_minibatches: 10
n_epochs: 4

gae_lambda: 0.95
gamma: 0.991
learning_rate: !!float 1e-4
clip_range: !!float 0.2
ent_coef: 0.005
vf_coef: 1.0
max_grad_norm: 1.0
normalize_input: True

use_sde: True
sde_sample_freq: 4 

policy_kwargs:
  activation_fn: 'nn.ELU'
  net_arch: [512, 256, 128]
  log_std_init: -1.5
  optimizer_kwargs:
    eps: !!float 1e-8
  ortho_init: False
  squash_output: True

device: "cuda:0"